using System.ComponentModel;
using ModHarmony.Common.Core;
using Terraria.ModLoader.Config;

namespace ModHarmony.Content.Config;

/// <summary>
/// ModHarmony's client-side configuration. The in-game config UI is generated by
/// tModLoader from these fields; labels/tooltips live in Localization/en-US.hjson.
/// </summary>
public class ModHarmonyConfig : ModConfig
{
	public override ConfigScope Mode => ConfigScope.ClientSide;

	// ------------------------------------------------------------- General

	[Header("$Mods.ModHarmony.Configs.Headers.General")]
	[DefaultValue(true)]
	[ReloadRequired]
	public bool EnableModHarmony;

	[DefaultValue(true)]
	public bool EnableDiagnostics;

	[DefaultValue(true)]
	[ReloadRequired]
	public bool RunStartupScan;

	[DefaultValue(false)]
	public bool RuntimeMonitoring;

	[DefaultValue(LogLevelSetting.Info)]
	public LogLevelSetting LogLevel;

	/// <summary>
	/// Detection only: disables arbitration application, keeps maximum diagnostics.
	/// </summary>
	[DefaultValue(false)]
	public bool SafeDiagnosticsMode;

	// ------------------------------------------------------------- Scanning

	[Header("$Mods.ModHarmony.Configs.Headers.Scanning")]
	[DefaultValue(true)]
	[ReloadRequired]
	public bool ScanHooks;

	[DefaultValue(true)]
	[ReloadRequired]
	public bool ScanGlobalClasses;

	[DefaultValue(true)]
	[ReloadRequired]
	public bool ScanRecipes;

	[DefaultValue(true)]
	[ReloadRequired]
	public bool ScanAssets;

	[DefaultValue(true)]
	[ReloadRequired]
	public bool ScanDependencies;

	[DefaultValue(true)]
	[ReloadRequired]
	public bool ScanILHooks;

	// ------------------------------------------------------------- Performance

	[Header("$Mods.ModHarmony.Configs.Headers.Performance")]
	[DefaultValue(200)]
	[Range(20, 2000)]
	[Increment(10)]
	public int MaxRetainedEvents;

	[DefaultValue(33)]
	[Range(16, 500)]
	[Increment(1)]
	[Slider]
	public int FrameSpikeThresholdMs;

	// ------------------------------------------------------------- Arbitration

	[Header("$Mods.ModHarmony.Configs.Headers.Arbitration")]
	[DefaultValue(false)]
	public bool EnableArbitration;

	[DefaultValue(ArbitrationStrategy.Disabled)]
	public ArbitrationStrategy DefaultStrategy;

	[DefaultValue(0)]
	public int RandomSeed;

	[DefaultValue(true)]
	public bool PersistDecisions;

	// ------------------------------------------------------------- UI

	[Header("$Mods.ModHarmony.Configs.Headers.UI")]
	[DefaultValue(false)]
	public bool ShowInformational;

	[DefaultValue(true)]
	public bool ShowLowRisk;

	[DefaultValue(false)]
	public bool DeveloperMode;

	[DefaultValue(false)]
	public bool CompactMode;

	/// <summary>Convenience: arbitration is only active when opted in and not in safe mode.</summary>
	public bool ArbitrationActive => EnableArbitration && !SafeDiagnosticsMode;

	/// <summary>
	/// Applies settings that should take effect immediately (no mod reload needed)
	/// and queues a rescan so detection results follow config changes.
	/// </summary>
	public override void OnChanged()
	{
		base.OnChanged();
		try {
			if (!Terraria.Main.dedServ) {
				Common.Diagnostics.RuntimeMonitor.SetActive(RuntimeMonitoring);
				Common.Diagnostics.PerformanceTracker.SetActive(RuntimeMonitoring);
			}
			Systems.ModHarmonySystem.QueueRescan();
		}
		catch {
			// Config changes must never break the game.
		}
	}
}

/// <summary>How verbose ModHarmony's own logging should be.</summary>
public enum LogLevelSetting
{
	Trace,
	Debug,
	Info,
	Warn,
	Error
}
